// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'control': string;
  'experimental-features': string;
  'experimentalFeatures': string;
}
declare let cssExports: CssExports;
export = cssExports;
