// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'charcoalGrey': string;
  'colorPrimary': string;
  'control': string;
  'controls': string;
  'dark': string;
  'darkWithOverlay': string;
  'map-navigation': string;
  'mapButtonColor': string;
  'mapNavigation': string;
  'modalHighlight': string;
  'navs': string;
  'with-time-series-controls': string;
  'withTimeSeriesControls': string;
}
declare var cssExports: CssExports;
export = cssExports;
