// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'charcoalGrey': string;
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'mapButtonColor': string;
  'menu': string;
  'menu-bar': string;
  'menu-bar--workbenchClosed': string;
  'menu-item': string;
  'menuBar': string;
  'menuBarWorkbenchClosed': string;
  'menuItem': string;
  'modalHighlight': string;
  'storyBtn': string;
  'textDarker': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
