// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'menu': string;
  'menu-area': string;
  'menu-area-left': string;
  'menu-area-left--workbenchClosed': string;
  'menu-area-right': string;
  'menu-item': string;
  'menuArea': string;
  'menuAreaLeft': string;
  'menuAreaLeftWorkbenchClosed': string;
  'menuAreaRight': string;
  'menuItem': string;
  'storyBtn': string;
}
declare var cssExports: CssExports;
export = cssExports;
