// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn--about-link': string;
  'btnAboutLink': string;
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'textDarker': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
