// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'complete': string;
  'progress-bar': string;
  'progressBar': string;
}
declare var cssExports: CssExports;
export = cssExports;
