// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'complete': string;
  'indeterminateAnimation': string;
  'progress-bar-determinate': string;
  'progress-bar-indeterminate': string;
  'progress-bar-value': string;
  'progressBarDeterminate': string;
  'progressBarIndeterminate': string;
  'progressBarValue': string;
}
declare var cssExports: CssExports;
export = cssExports;
