// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'complete': string;
  'indeterminate-bar-animated': string;
  'indeterminateAnimation': string;
  'indeterminateBarAnimated': string;
  'progress-bar': string;
  'progressBar': string;
}
declare let cssExports: CssExports;
export = cssExports;
