// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'divider': string;
  'divider-wrapper': string;
  'dividerWrapper': string;
  'textDarker': string;
  'textLight': string;
  'thumb': string;
}
declare var cssExports: CssExports;
export = cssExports;
