// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cesium-container': string;
  'cesiumContainer': string;
  'container': string;
  'mapPlaceholder': string;
}
declare var cssExports: CssExports;
export = cssExports;
