// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'charcoalGrey': string;
  'colorPrimary': string;
  'content': string;
  'dark': string;
  'darkWithOverlay': string;
  'isActive': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'window': string;
}
declare var cssExports: CssExports;
export = cssExports;
