// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'btn': string;
  'footer': string;
  'inner': string;
  'notification': string;
  'title': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
