// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'btn': string;
  'charcoalGrey': string;
  'colorPrimary': string;
  'dark': string;
  'darkWithOverlay': string;
  'footer': string;
  'inner': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'notification': string;
  'title': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
