// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'charcoalGrey': string;
  'colorPrimary': string;
  'colorSplitter': string;
  'compassWidth': string;
  'dark': string;
  'darkWithOverlay': string;
  'frontComponentZIndex': string;
  'grey': string;
  'greyLighter': string;
  'greyLighter2': string;
  'greyLightest': string;
  'lg': string;
  'mapButtonColor': string;
  'mapButtonTop': string;
  'mapNavigationTop': string;
  'md': string;
  'mobile': string;
  'modalBg': string;
  'modalHighlight': string;
  'modalText': string;
  'overlay': string;
  'overlayInvert': string;
  'radius40Button': string;
  'radiusLarge': string;
  'radiusSmall': string;
  'ringWidth': string;
  'sm': string;
  'spacing': string;
  'textBlack': string;
  'textDark': string;
  'textDarker': string;
  'textLight': string;
  'textLightDimmed': string;
  'trainerHeight': string;
  'workbenchWidth': string;
}
declare var cssExports: CssExports;
export = cssExports;
