// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'filename': string;
  'icon': string;
  'info': string;
  'isActive': string;
  'notification': string;
}
declare var cssExports: CssExports;
export = cssExports;
