// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'caption': string;
  'drop-zone': string;
  'dropZone': string;
  'heading': string;
  'inner': string;
  'is-active': string;
  'isActive': string;
}
declare var cssExports: CssExports;
export = cssExports;
