// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottom-dock': string;
  'bottomDock': string;
}
declare let cssExports: CssExports;
export = cssExports;
