// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'formLabel': string;
  'searchClear': string;
  'searchData': string;
  'searchField': string;
}
declare let cssExports: CssExports;
export = cssExports;
