// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'no-results': string;
  'noResults': string;
}
declare var cssExports: CssExports;
export = cssExports;
