// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'base': string;
  'fade-out': string;
  'fade-out-clone': string;
  'fadeOut': string;
  'fadeOutClone': string;
  'inner': string;
  'innerClone': string;
  'oval': string;
}
declare var cssExports: CssExports;
export = cssExports;
