// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'context': string;
  'guidance': string;
  'indicator': string;
  'indicatorEnabled': string;
  'indicatorWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
