// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'charcoalGrey': string;
  'colorPrimary': string;
  'dark': string;
  'darkWithOverlay': string;
  'mapButtonColor': string;
  'message-item': string;
  'messageItem': string;
  'modalHighlight': string;
  'sections': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
