// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'download': string;
  'dropdownButton': string;
  'dropdownList': string;
  'dropdown__button': string;
  'dropdown__list': string;
  'icon--download': string;
  'iconDownload': string;
  'textDarker': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
