// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'download': string;
  'dropdownButton': string;
  'dropdownList': string;
  'dropdown__button': string;
  'dropdown__list': string;
  'icon--download': string;
  'iconDownload': string;
}
export const cssExports: CssExports;
export default cssExports;
