// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'charcoalGrey': string;
  'colorPrimary': string;
  'content': string;
  'dark': string;
  'darkWithOverlay': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'raw-data-button': string;
  'rawDataButton': string;
  'section': string;
  'time-series-chart': string;
  'timeSeriesChart': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
