// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'charcoalGrey': string;
  'colorPrimary': string;
  'dark': string;
  'darkWithOverlay': string;
  'download': string;
  'dropdownButton': string;
  'dropdownList': string;
  'dropdown__button': string;
  'dropdown__list': string;
  'icon--download': string;
  'iconDownload': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'textDarker': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
