// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'message-item': string;
  'messageItem': string;
  'sections': string;
}
export const cssExports: CssExports;
export default cssExports;
