// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'leftDatePickerPopup': string;
  'rightDatePickerPopup': string;
}
declare var cssExports: CssExports;
export = cssExports;
