// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dropdown-inner': string;
  'dropdownInner': string;
  'image': string;
  'link': string;
  'section': string;
}
export const cssExports: CssExports;
export default cssExports;
