[build]
  command = "yarn gulp docs"
  publish = "wwwroot/doc"
[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NETLIFY_USE_YARN = "true"
  PYTHON_VERSION = "3.8" 
