// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'charcoalGrey': string;
  'colorPrimary': string;
  'colorSplitter': string;
  'controls': string;
  'dark': string;
  'darkWithOverlay': string;
  'is-active': string;
  'isActive': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'textDarker': string;
  'textLight': string;
  'timelineControl': string;
  'timeline__control': string;
}
declare var cssExports: CssExports;
export = cssExports;
