// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  activeGrid: string;
  backbtn: string;
  backbutton: string;
  centuryBtn: string;
  controlsRow: string;
  dateBtn: string;
  datePicker: string;
  dayPicker: string;
  field: string;
  grid: string;
  gridBody: string;
  gridHeading: string;
  gridLabel: string;
  gridRow: string;
  gridRowInner12: string;
  gridRowInner31: string;
  inactiveGridRow: string;
  openBelow: string;
  "style-selector": string;
  styleSelector: string;
  summary: string;
  "text-cell": string;
  "text-row": string;
  textCell: string;
  textRow: string;
  time: string;
  timeline: string;
  timelineDatePicker: string;
  title: string;
  togglebutton: string;
}
declare var cssExports: CssExports;
export = cssExports;
