// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'controls': string;
  'is-active': string;
  'isActive': string;
  'timelineControl': string;
  'timeline__control': string;
}
declare let cssExports: CssExports;
export = cssExports;
