// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn--dropdown': string;
  'btn--option': string;
  'btnDropdown': string;
  'btnOption': string;
  'dropdown': string;
  'is-open': string;
  'is-selected': string;
  'isOpen': string;
  'isSelected': string;
  'list': string;
  'myDataDropdown': string;
}
export const cssExports: CssExports;
export default cssExports;
