// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'isVisible': string;
  'prompt': string;
}
declare var cssExports: CssExports;
export = cssExports;
