// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badge': string;
  'map': string;
  'placeholder': string;
  'terria-preview': string;
  'terriaPreview': string;
}
declare var cssExports: CssExports;
export = cssExports;
