// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn--back-to-map': string;
  'btnBackToMap': string;
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'field': string;
  'h3': string;
  'h4': string;
  'placeholder': string;
  'preview': string;
  'preview-chart': string;
  'previewChart': string;
  'previewInner': string;
  'preview__inner': string;
  'textDarker': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
