// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badge': string;
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'map': string;
  'placeholder': string;
  'terria-preview': string;
  'terriaPreview': string;
  'textDarker': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
