// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badge': string;
  'charcoalGrey': string;
  'colorPrimary': string;
  'dark': string;
  'darkWithOverlay': string;
  'map': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'placeholder': string;
  'terria-preview': string;
  'terriaPreview': string;
  'textDarker': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
