// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn--add': string;
  'btnAdd': string;
  'description': string;
  'error': string;
  'field': string;
  'h4': string;
  'heading': string;
  'metadata': string;
  'previewed--info': string;
  'previewedInfo': string;
  'share-link--wrapper': string;
  'shareLinkWrapper': string;
  'subHeading': string;
  'title-and-share-wrapper': string;
  'titleAndShareWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
