// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alert-message': string;
  'alertMessage': string;
  'btn--add': string;
  'btnAdd': string;
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'description': string;
  'error': string;
  'field': string;
  'h3': string;
  'h4': string;
  'link': string;
  'metadata': string;
  'previewed--info': string;
  'previewedInfo': string;
  'share-link--wrapper': string;
  'shareLinkWrapper': string;
  'textDarker': string;
  'textLight': string;
  'title-and-share-wrapper': string;
  'titleAndShareWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
