// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'base-map-selector': string;
  'baseMapSelector': string;
  'btn--viewer': string;
  'btnViewer': string;
  'dropdown-inner': string;
  'dropdownInner': string;
  'field': string;
  'is-active': string;
  'isActive': string;
  'link': string;
  'link-wrapper': string;
  'linkWrapper': string;
  'list-item': string;
  'listItem': string;
  'paragraph': string;
  'share-panel': string;
  'sharePanel': string;
  'shorten-url': string;
  'shortenUrl': string;
  'viewer-selector': string;
  'viewerSelector': string;
}
declare var cssExports: CssExports;
export = cssExports;
