// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dropdown-inner': string;
  'dropdownInner': string;
}
declare let cssExports: CssExports;
export = cssExports;
