// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'enter': string;
  'enter-active': string;
  'enterActive': string;
  'exit': string;
  'exit-active': string;
  'exitActive': string;
}
declare var cssExports: CssExports;
export = cssExports;
