// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'crs--item': string;
  'crsItem': string;
  'dropdown-inner': string;
  'dropdownInner': string;
  'explanation': string;
  'format-button': string;
  'formatButton': string;
  'shareUrlfield': string;
}
declare var cssExports: CssExports;
export = cssExports;
