// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'panel-content': string;
  'panelContent': string;
  'tab-list': string;
  'tab-list__item': string;
  'tab-panel': string;
  'tabList': string;
  'tabListItem': string;
  'tabPanel': string;
}
declare var cssExports: CssExports;
export = cssExports;
