// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'data-explorer': string;
  'dataExplorer': string;
  'root': string;
}
declare var cssExports: CssExports;
export = cssExports;
