// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'btnPanelHeading': string;
  'buttonRow': string;
  'fieldGroup': string;
  'header': string;
  'headerContent': string;
  'headerIcon': string;
  'is-collapsed': string;
  'is-loading': string;
  'is-translucent': string;
  'is-visible': string;
  'isCollapsed': string;
  'isLoading': string;
  'isTranslucent': string;
  'isVisible': string;
  'loadingIndicator': string;
  'messageBox': string;
  'messageError': string;
  'messageInfo': string;
  'panel': string;
  'pulse': string;
}
declare var cssExports: CssExports;
export = cssExports;
