// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bold': string;
  'medium': string;
  'text': string;
}
declare var cssExports: CssExports;
export = cssExports;
