// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dropdownList': string;
  'dropdown__list': string;
  'inner': string;
  'label': string;
  'tab-panel': string;
  'tab-panels': string;
  'tabHeading': string;
  'tabPanel': string;
  'tabPanels': string;
  'url-input': string;
  'url-input__btn': string;
  'url-input__text-box': string;
  'urlInput': string;
  'urlInputBtn': string;
  'urlInputTextBox': string;
}
declare var cssExports: CssExports;
export = cssExports;
