// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'charcoalGrey': string;
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'dropdownList': string;
  'dropdown__list': string;
  'inner': string;
  'label': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'tab-panel': string;
  'tab-panels': string;
  'tabHeading': string;
  'tabPanel': string;
  'tabPanels': string;
  'textDarker': string;
  'textLight': string;
  'url-input': string;
  'url-input__btn': string;
  'url-input__text-box': string;
  'urlInput': string;
  'urlInputBtn': string;
  'urlInputTextBox': string;
}
declare var cssExports: CssExports;
export = cssExports;
