// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add-asset-button': string;
  'addAssetButton': string;
  'assets-list': string;
  'assetsList': string;
  'connect-button': string;
  'connectButton': string;
  'drop-down': string;
  'drop-down-button': string;
  'dropDown': string;
  'dropDownButton': string;
  'token-warning': string;
  'token-warning-hidden': string;
  'tokenWarning': string;
  'tokenWarningHidden': string;
}
declare var cssExports: CssExports;
export = cssExports;
