// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'connect-button': string;
  'connectButton': string;
}
declare var cssExports: CssExports;
export = cssExports;
