// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'btn--hover': string;
  'btnHover': string;
  'charcoalGrey': string;
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'file-input': string;
  'fileInput': string;
  'input': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'textDarker': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
