// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'btn--hover': string;
  'btnHover': string;
  'file-input': string;
  'fileInput': string;
  'input': string;
}
declare var cssExports: CssExports;
export = cssExports;
