// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addData': string;
  'body': string;
  'button': string;
  'header': string;
  'uploadData': string;
  'workbenchEmpty': string;
}
declare var cssExports: CssExports;
export = cssExports;
