// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addData': string;
  'body': string;
  'button': string;
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'header': string;
  'textDarker': string;
  'textLight': string;
  'uploadData': string;
  'workbenchEmpty': string;
}
declare var cssExports: CssExports;
export = cssExports;
