// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'WelcomeModal': string;
  'WelcomeModal-body': string;
  'WelcomeModal-button': string;
  'WelcomeModal-buttonPrimary': string;
  'WelcomeModal-buttonTertiary': string;
  'WelcomeModal-closeLink': string;
  'WelcomeModalWrapper': string;
  'close-btn': string;
  'closeBtn': string;
  'highlight': string;
  'welcomeModal': string;
  'welcomeModalBody': string;
  'welcomeModalButton': string;
  'welcomeModalButtonPrimary': string;
  'welcomeModalButtonTertiary': string;
  'welcomeModalCloseLink': string;
  'welcomeModalWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
