// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'btn': string;
  'charcoalGrey': string;
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'header': string;
  'is-inverse': string;
  'is-open': string;
  'isInverse': string;
  'isOpen': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'root': string;
  'textDarker': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
