// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'btn-add': string;
  'btn-now-viewing': string;
  'btn-search': string;
  'btnAdd': string;
  'btnNowViewing': string;
  'btnSearch': string;
  'doubleDigit': string;
  'formSearchData': string;
  'group-left': string;
  'group-right': string;
  'groupLeft': string;
  'groupRight': string;
  'mobile-header': string;
  'mobileHeader': string;
  'nowViewingCount': string;
  'ui': string;
}
declare var cssExports: CssExports;
export = cssExports;
