// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn--about-link': string;
  'btnAboutLink': string;
}
export const cssExports: CssExports;
export default cssExports;
