// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'btnCancel': string;
  'btnClose': string;
  'btnSubmit': string;
  'btnSubmit--hover': string;
  'btnSubmitHover': string;
  'description': string;
  'field': string;
  'form': string;
  'header': string;
  'isOpen': string;
  'label': string;
  'share-url': string;
  'shareUrl': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
