// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnFeedback': string;
  'charcoalGrey': string;
  'colorPrimary': string;
  'dark': string;
  'darkWithOverlay': string;
  'feedback': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'textDarker': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
