// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  btnFeedback: string;
  feedback: string;
}
declare var cssExports: CssExports;
export = cssExports;
