// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnList': string;
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'data': string;
  'items': string;
  'label': string;
  'location': string;
  'provider-result': string;
  'providerResult': string;
  'results': string;
  'textDarker': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
