// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnList': string;
  'data': string;
  'items': string;
  'label': string;
  'location': string;
  'provider-result': string;
  'providerResult': string;
  'results': string;
}
export const cssExports: CssExports;
export default cssExports;
