// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'back-button': string;
  'back-button--inactive': string;
  'backButton': string;
  'backButtonInactive': string;
  'button': string;
  'data-catalog': string;
  'dataCatalog': string;
  'done-button': string;
  'doneButton': string;
  'icon-back': string;
  'iconBack': string;
  'isOpen': string;
  'mobileModal': string;
  'modal-top': string;
  'modalBg': string;
  'modalTop': string;
}
declare var cssExports: CssExports;
export = cssExports;
