// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'mobile-nav': string;
  'mobile-nav--hidden': string;
  'mobileNav': string;
  'mobileNavHidden': string;
  'overlay': string;
}
export const cssExports: CssExports;
export default cssExports;
