// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'link': string;
  'root': string;
}
declare let cssExports: CssExports;
export = cssExports;
