// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dark': string;
  'input': string;
  'large': string;
  'light': string;
}
declare var cssExports: CssExports;
export = cssExports;
