// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'data--catalog-group': string;
  'data-catalog': string;
  'data-explorer': string;
  'dataCatalog': string;
  'dataCatalogGroup': string;
  'dataExplorer': string;
  'label': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
