// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'data--catalog-group': string;
  'data-catalog': string;
  'data-explorer': string;
  'dataCatalog': string;
  'dataCatalogGroup': string;
  'dataExplorer': string;
  'label': string;
  'root': string;
  'textDarker': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
