// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'category': string;
  'column': string;
  'enter': string;
  'enterActive': string;
  'enterDone': string;
  'exit': string;
  'exitActive': string;
  'exitDone': string;
  'name': string;
  'tooltip': string;
  'tooltipRow': string;
}
declare var cssExports: CssExports;
export = cssExports;
