// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  "chart-td": string;
  "chart-title-from-table": string;
  chartTd: string;
  chartTitleFromTable: string;
  "preview-chart-wrapper": string;
  previewChartWrapper: string;
}
declare var cssExports: CssExports;
export = cssExports;
