// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn-download': string;
  'btnDownload': string;
}
export const cssExports: CssExports;
export default cssExports;
