// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chart-td': string;
  'chart-title-from-table': string;
  'chartTd': string;
  'chartTitleFromTable': string;
  'preview-chart': string;
  'preview-chart-wrapper': string;
  'previewChart': string;
  'previewChartWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
