// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  chart: string;
  concepts: string;
  conceptsList: string;
  "tool-tip": string;
  toolTip: string;
}
declare var cssExports: CssExports;
export = cssExports;
