// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'a--download': string;
  'aDownload': string;
  'btn--chart-expand': string;
  'btn--dropdown': string;
  'btn-download': string;
  'btn-small': string;
  'btnChartExpand': string;
  'btnDownload': string;
  'btnDropdown': string;
  'btnSmall': string;
  'chart-dropdown-button': string;
  'chart-expand': string;
  'chartDropdownButton': string;
  'chartExpand': string;
  'dropdown': string;
  'dropdownBtn': string;
  'dropdownBtnOption': string;
  'dropdownList': string;
  'dropdown__btn': string;
  'dropdown__btn--option': string;
  'dropdown__list': string;
  'raise-to-title': string;
  'raiseToTitle': string;
}
declare var cssExports: CssExports;
export = cssExports;
