// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn-download': string;
  'btnDownload': string;
}
declare let cssExports: CssExports;
export = cssExports;
