// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn--dropdown': string;
  'btn-download': string;
  'btn-small': string;
  'btnDownload': string;
  'btnDropdown': string;
  'btnSmall': string;
  'dropdown': string;
  'dropdownBtn': string;
  'dropdownBtnOption': string;
  'dropdownList': string;
  'dropdown__btn': string;
  'dropdown__btn--option': string;
  'dropdown__list': string;
}
declare var cssExports: CssExports;
export = cssExports;
