// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'enter': string;
  'enterActive': string;
  'exit': string;
  'exitActive': string;
  'group': string;
  'item': string;
  'itemName': string;
  'itemSymbol': string;
  'itemValue': string;
  'textDarker': string;
  'textLight': string;
  'tooltip': string;
}
declare var cssExports: CssExports;
export = cssExports;
