// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'group': string;
  'item': string;
  'itemName': string;
  'itemSymbol': string;
  'itemValue': string;
  'tooltip': string;
  'transition-enter': string;
  'transition-enter-active': string;
  'transition-exit': string;
  'transition-exit-active': string;
  'transitionEnter': string;
  'transitionEnterActive': string;
  'transitionExit': string;
  'transitionExitActive': string;
}
declare var cssExports: CssExports;
export = cssExports;
