import CatalogMemberTraits from "./CatalogMemberTraits";
import MappableTraits from "./MappableTraits";
import mixTraits from "../mixTraits";
import primitiveTrait from "../Decorators/primitiveTrait";
import UrlTraits from "./UrlTraits";
import { traitClass } from "../Trait";

@traitClass({
  description: `Creates a Cesium terrain item in the catalog from url.`,
  example: {
    type: "cesium-terrain",
    description:
      "This product is a terrain, it provides a representation of the earth's surface with which to apply data in Digital Twin Victoria. The terrain has been generated by transforming Vicmap Elevation digital elevation models (DEMs) into a quantized-mesh terrain tileset. The combined Vicmap elevation extent is embedded in ‘Cesium World Terrain’. These DEMs include ‘Vicmap Elevation DEM 10m’ which provides a base for state-wide coverage. Where available 1m DEMs have been embedded over the ‘Vicmap Elevation DEM 10m’ product. These include:<small><ul><li>Ararat:<small> 2018-19_cep31-2018-19_3d-regional-towns-lidar_ararat</small></li><li> Ballarat:<small> 2018-19_cep31-2018-19_3d-regional-towns-lidar_ballarat</small></li><li> Bendigo:<small> 2018-19_cep31-2018-19_3d-regional-towns-lidar_bendigo</small></li><li> Bright:<small> 2018-19_cep31-2018-19_3d-regional-towns-lidar_bright</small></li><li> Castlemaine:<small> 2018-19_cep31-2018-19_3d-regional-towns-lidar_castlemaine</small></li><li> Echuca:<small> 2018-19_cep31-2018-19_3d-regional-towns-lidar_echuca</small></li><li> Golden Plains:<small> 2020-21_cep24-2020-21_golden-plains_lidar</small></li><li> Great Ocean Road:<small> 2019-20_cep27-2019-20_great_ocean_road_elevation</small></li><li> Horsham:<small> 2018-19_cep31-2018-19_3d-regional-towns-lidar_horsham</small></li><li> Kilmore:<small> 2018-19_cep31-2018-19_3d-regional-towns-lidar_kilmore</small></li><li> Latrobe Valley:<small> 2018-19_cep31-2018-19_3d-regional-towns-lidar_latrobevalley</small></li><li> Melbourne:<small> 2017-18_greater_melbourne_lidar_project-01-2017-18</small></li><li> Mildura:<small> 2020-21_cep21-2020-21_mildura-towns-lidar_mildura</small></li><li> Sale:<small> 2018-19_cep31-2018-19_3d-regional-towns-lidar_sale</small></li><li> Seymour:<small> 2018-19_cep31-2018-19_3d-regional-towns-lidar_seymour</small></li><li> Shepparton:<small> 2018-19_cep31-2018-19_3d-regional-towns-lidar_shepparton</small></li><li> Swan Hill:<small> 2018-19_cep31-2018-19_3d-regional-towns-lidar_swanhill</small></li><li> Traralgon:<small> 2018-19_cep31-2018-19_3d-regional-towns-lidar_traralgon</small></li><li> Wangaratta:<small> 2018-19_cep31-2018-19_3d-regional-towns-lidar_wangaratta</small></li><li> Warracknabeal:<small> 2018-19_cep31-2018-19_3d-regional-towns-lidar_warracknabeal</small></li><li> Warrnambool:<small> 2016-17_cep19-2016-17_warrnambool-city</small></li><li> Wodonga:<small> cep28-2016-17_north-east-towns-lidar_wodonga</small></li><li>Wonthaggi:<small> 2018-19_cep31-2018-19_3d-regional-towns-lidar_wonthaggi</small></li></ul>",
    url: "https://storage.googleapis.com/vic-datasets-public/85b71982-f5fe-4093-b4e4-fd2e50198fba/v2",
    name: "A Vic Terrain",
    id: "some-unique-id"
  }
})
export default class CesiumTerrainCatalogItemTraits extends mixTraits(
  UrlTraits,
  MappableTraits,
  CatalogMemberTraits
) {
  @primitiveTrait({
    name: "Ion Asset ID",
    type: "number",
    description: "The ID of the Cesium Ion Asset. If this is set url is ignored"
  })
  ionAssetId?: number;

  @primitiveTrait({
    name: "Ion Access Token",
    type: "string",
    description:
      "The Cesium Ion access token to use to access the terrain. If not specified, the token"
  })
  ionAccessToken?: string;

  @primitiveTrait({
    name: "Ion Server",
    type: "string",
    description:
      "the Cesium Ion access token to use to access the terrain. If not specified, the default Ion server, `https://api.cesium.com/`"
  })
  ionServer?: string;
}
