// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn--done': string;
  'btnDone': string;
  'btnList': string;
  'colorPrimary': string;
  'colorSecondary': string;
  'dark': string;
  'darkWithOverlay': string;
  'greyLightest': string;
  'heading': string;
  'items': string;
  'provider-result': string;
  'providerResult': string;
  'results': string;
  'results-content': string;
  'resultsContent': string;
}
declare var cssExports: CssExports;
export = cssExports;
