// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'cancel': string;
  'delete': string;
  'footer': string;
  'inner': string;
  'outer-div': string;
  'outerDiv': string;
  'popup': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
