const brandMapping = {
  "de-aust": {
    branding: [
      "",
      '<a target="_blank" href="http://terria.io"><img src="https://maps.dea.ga.gov.au/images/DE-Australia-logo.png" height="52" title="Version: {{version}}" /></a>',
      "<a id='secondary-logo' href='https://data61.csiro.au/' target='_blank'><img class='right' style=\"width:65px;\" src='https://maps.dea.ga.gov.au/images/data61-csiro.svg' alt='Data61 logo' title='Data61 logo'/></a>",
      "<a id='tertiary-logo' target='https://www.ga.gov.au/' rel='noreferrer noopener'><img src='https://maps.dea.ga.gov.au/images/geoscience_stacked.svg' style=\"width: 80px;\"  alt='Geoscience Australia logo' title='Geoscience Australia logo'/></a>",
      ""
    ],
    theme: {
      charcoalGrey: "#3f4854",
      colorPrimary: "#00a1de",
      colorSplitter: "#ff6f00",
      compassWidth: "56",
      dark: "#3f4854",
      frontComponentZIndex: "99",
      grey: "#888888",
      greyLighter: "#ddd",
      greyLighter2: "#e6e6e6",
      greyLightest: "#f2f2f2",
      lg: "1300",
      mapButtonColor: "#9ca1aa",
      md: "992",
      mobile: "767",
      modalHighlight: "#00a1de",
      overlay: "rgba(255, 255, 255, 0.15)",
      overlayInvert: "rgba(255, 255, 255, 0.85)",
      primary: "#00a1de",
      radius40Button: "20",
      radiusLarge: "4px",
      radiusSmall: "2px",
      ringWidth: "10",
      secondary: "#8fcae7",
      sm: "768",
      spacing: "5",
      text: "#fff",
      textBlack: "#000",
      textDark: "#595b60",
      textDarker: "#4d5766",
      textLight: "#ffffff",
      textLightDimmed: "#bbbbbb",
      workbenchWidth: "350"
    }
  },
  "de-africa": {
    branding: [
      "",
      '<a target="_blank" href="http://terria.io"><img src="https://maps.digitalearth.africa/images/DE-Africa-logo.png" height="52" title="Version: {{version}}" /></a>',
      "<a id='secondary-logo' href='https://data61.csiro.au/' target='_blank'><img class='right' style=\"width:50px; padding: 0 5px;\" src='https://maps.digitalearth.africa/images/data61-csiro.svg' alt='Data61 logo' title='Data61 logo'/></a>",
      "<a id='tertiary-logo' target='_blank' rel='noreferrer noopener'><img src='https://maps.digitalearth.africa/images/deafrica-prototype.svg' style=\"width: 130px;\"  alt='DE Africa logo' title='DE Africa logo'/></a>",
      ""
    ],
    theme: {
      charcoalGrey: "#3f4854",
      colorPrimary: "#eeaf30",
      colorSplitter: "#ff6f00",
      compassWidth: "56",
      dark: "#000",
      darkWithOverlay: "#333",
      frontComponentZIndex: "99",
      grey: "#888888",
      greyLighter: "#ddd",
      greyLighter2: "#e6e6e6",
      greyLightest: "#f2f2f2",
      lg: "1300",
      mapButtonColor: "#9ca1aa",
      md: "992",
      mobile: "767",
      modalHighlight: "#8fcae7",
      overlay: "rgba(255, 255, 255, 0.15)",
      overlayInvert: "rgba(255, 255, 255, 0.85)",
      primary: "#eeaf30",
      radius40Button: "20",
      radiusLarge: "4px",
      radiusSmall: "2px",
      ringWidth: "10",
      secondary: "#8fcae7",
      sm: "768",
      spacing: "5",
      text: "#fff",
      textBlack: "#000",
      textDark: "#595b60",
      textDarker: "#4d5766",
      textLight: "#ffffff",
      textLightDimmed: "#bbbbbb",
      workbenchWidth: "350"
    }
  }
};
export default brandMapping;
