// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'charcoalGrey': string;
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'feedback': string;
  'feedback-button-wrapper': string;
  'feedbackButtonWrapper': string;
  'location-distance': string;
  'locationDistance': string;
  'map-cell-map': string;
  'map-wrapper': string;
  'mapButtonColor': string;
  'mapCell': string;
  'mapCellChrome': string;
  'mapCellMap': string;
  'mapInner': string;
  'mapInnerChrome': string;
  'mapRow': string;
  'mapWrapper': string;
  'map__cell': string;
  'map__cellChrome': string;
  'map__inner': string;
  'map__innerChrome': string;
  'map__row': string;
  'modalHighlight': string;
  'print-disclaimer': string;
  'printDisclaimer': string;
  'textDarker': string;
  'textLight': string;
  'with-time-series-controls': string;
  'withTimeSeriesControls': string;
}
declare var cssExports: CssExports;
export = cssExports;
