// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  feedback: string;
  "feedback-button-wrapper": string;
  feedbackButtonWrapper: string;
  "location-distance": string;
  locationDistance: string;
  "map-cell-map": string;
  "map-wrapper": string;
  mapCell: string;
  mapCellMap: string;
  mapInner: string;
  mapRow: string;
  mapWrapper: string;
  map__cell: string;
  map__inner: string;
  map__row: string;
  "print-disclaimer": string;
  printDisclaimer: string;
  "with-time-series-controls": string;
  withTimeSeriesControls: string;
}
declare var cssExports: CssExports;
export = cssExports;
