// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'explorerPanelIsVisible': string;
  'featureInfo': string;
  'featureInfoFullScreen': string;
  'feedback': string;
  'map': string;
  'showWorkbenchButton': string;
  'showWorkbenchButtonTrainerBarVisible': string;
  'showWorkbenchButtonisNotVisible': string;
  'showWorkbenchButtonisVisible': string;
  'sidePanel': string;
  'story-wrapper': string;
  'storyWrapper': string;
  'ui': string;
  'ui-root': string;
  'uiInner': string;
  'uiRoot': string;
}
declare var cssExports: CssExports;
export = cssExports;
