// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'results': string;
  'submit': string;
  'toolsPanel': string;
}
declare var cssExports: CssExports;
export = cssExports;
