// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'btn': string;
  'header': string;
  'is-inverse': string;
  'is-open': string;
  'isInverse': string;
  'isOpen': string;
  'root': string;
}
declare var cssExports: CssExports;
export = cssExports;
