// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn--catalogShare': string;
  'btn--withoutText': string;
  'btnCatalogShare': string;
  'btnWithoutText': string;
  'catalog-share': string;
  'catalog-share-inner': string;
  'catalogShare': string;
  'catalogShareInner': string;
  'dropdown-inner': string;
  'dropdownInner': string;
  'share-panel': string;
  'sharePanel': string;
  'story-share': string;
  'story-share-inner': string;
  'storyShare': string;
  'storyShareInner': string;
}
declare var cssExports: CssExports;
export = cssExports;
