version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    cooldown:
      default-days: 5
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    versioning-strategy: increase
    cooldown:
      default-days: 5
