// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'btnPanelHeading': string;
  'header': string;
  'is-collapsed': string;
  'is-translucent': string;
  'is-visible': string;
  'isCollapsed': string;
  'isTranslucent': string;
  'isVisible': string;
  'panel': string;
}
declare var cssExports: CssExports;
export = cssExports;
