// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background-circle': string;
  'backgroundCircle': string;
  'elapsedTime': string;
  'timer': string;
}
declare let cssExports: CssExports;
export = cssExports;
