// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'charcoalGrey': string;
  'close-btn': string;
  'closeBtn': string;
  'colorPrimary': string;
  'dark': string;
  'darkWithOverlay': string;
  'help-panel': string;
  'help-panel-shifted': string;
  'helpPanel': string;
  'helpPanelShifted': string;
  'is-selected': string;
  'isSelected': string;
  'link': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'panel-item': string;
  'panelItem': string;
  'story-fade-in': string;
  'story-fade-out': string;
  'story-slide-down': string;
  'story-slide-up': string;
  'storyFadeIn': string;
  'storyFadeOut': string;
  'storySlideDown': string;
  'storySlideUp': string;
  'tourBtn': string;
  'video-panel': string;
  'videoBtn': string;
  'videoGuide': string;
  'videoGuide--iframe': string;
  'videoGuideIframe': string;
  'videoGuideLoading': string;
  'videoGuideRatio': string;
  'videoGuideWrapperFullScreen': string;
  'videoLink': string;
  'videoPanel': string;
}
declare var cssExports: CssExports;
export = cssExports;
