// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'VideoGuideWrapper': string;
  'VideoGuideWrapper--closing': string;
  'charcoalGrey': string;
  'close-btn': string;
  'closeBtn': string;
  'colorPrimary': string;
  'dark': string;
  'darkWithOverlay': string;
  'help-panel': string;
  'help-panel-shifted': string;
  'helpPanel': string;
  'helpPanelShifted': string;
  'is-selected': string;
  'isHidden': string;
  'isSelected': string;
  'isVisible': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'panel-item': string;
  'panelItem': string;
  'story-fade-in': string;
  'story-fade-out': string;
  'story-slide-down': string;
  'story-slide-up': string;
  'storyFadeIn': string;
  'storyFadeOut': string;
  'storySlideDown': string;
  'storySlideUp': string;
  'textDarker': string;
  'textLight': string;
  'tourBtn': string;
  'video-panel': string;
  'videoGuide': string;
  'videoGuide--iframe': string;
  'videoGuideIframe': string;
  'videoGuideLoading': string;
  'videoGuideRatio': string;
  'videoGuideWrapper': string;
  'videoGuideWrapperClosing': string;
  'videoPanel': string;
}
declare var cssExports: CssExports;
export = cssExports;
