// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'content': string;
  'isActive': string;
  'window': string;
}
declare var cssExports: CssExports;
export = cssExports;
