// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'bodyFooter': string;
  'bodyProgress': string;
  'btn': string;
  'btn--tertiary': string;
  'btn-next': string;
  'btnNext': string;
  'btnTertiary': string;
  'charcoalGrey': string;
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'guide': string;
  'image': string;
  'image-wrapper': string;
  'imageWrapper': string;
  'indicator': string;
  'indicatorEnabled': string;
  'indicatorWrapper': string;
  'inner-close-btn': string;
  'innerCloseBtn': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'textDarker': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
