// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn--close-modal': string;
  'btnCloseModal': string;
  'explorer-panel': string;
  'explorerPanel': string;
  'is-mounted': string;
  'isMounted': string;
  'modal-overlay': string;
  'modal-wrapper': string;
  'modalOverlay': string;
  'modalWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
