// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn--selected': string;
  'btn--tab': string;
  'btnSelected': string;
  'btnTab': string;
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'panel-content': string;
  'panelContent': string;
  'tab-left-col': string;
  'tab-list': string;
  'tab-list__item': string;
  'tab-panel': string;
  'tabLeftCol': string;
  'tabList': string;
  'tabListItem': string;
  'tabPanel': string;
  'tabs': string;
  'textDarker': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
