// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionsRow': string;
  'detailHeading': string;
  'detailSection': string;
  'detailTable': string;
  'detailWrapper': string;
  'emergencyPlansLink': string;
  'emptyState': string;
  'error': string;
  'field': string;
  'fieldLabel': string;
  'filterGrid': string;
  'notice': string;
  'resizeHandle': string;
  'rowClickable': string;
  'rowSelected': string;
  'sectionTitle': string;
  'table': string;
  'tableWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
