// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn--catalog': string;
  'btnCatalog': string;
  'btnCatalogTopLevel': string;
  'caret': string;
  'catalog-group': string;
  'catalog-group--lower-level': string;
  'catalogGroup': string;
  'catalogGroupLowerLevel': string;
  'folder': string;
  'label': string;
  'label--no-results': string;
  'labelNoResults': string;
  'offsetRight': string;
  'root': string;
  'trashGroup': string;
}
declare var cssExports: CssExports;
export = cssExports;
