// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  "btn-action": string;
  "btn-action--loading-on-map": string;
  "btn-catalog-item": string;
  "btn-catalog-item--is-previewed": string;
  btnAction: string;
  btnActionLoadingOnMap: string;
  btnCatalogItem: string;
  btnCatalogItemIsPreviewed: string;
  root: string;
}
declare var cssExports: CssExports;
export = cssExports;
