// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'data-catalog': string;
  'dataCatalog': string;
  'label': string;
}
declare var cssExports: CssExports;
export = cssExports;
