// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn--catalog': string;
  'btnCatalog': string;
  'btnCatalogTopLevel': string;
  'caret': string;
  'catalog-group': string;
  'catalog-group--lower-level': string;
  'catalogGroup': string;
  'catalogGroupLowerLevel': string;
  'charcoalGrey': string;
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'folder': string;
  'isPreviewed': string;
  'label': string;
  'label--no-results': string;
  'labelNoResults': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'offsetRight': string;
  'root': string;
  'textDarker': string;
  'textLight': string;
  'trashGroup': string;
}
declare var cssExports: CssExports;
export = cssExports;
