// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'enter': string;
  'exit': string;
  'full-screen': string;
  'fullScreen': string;
  'isActive': string;
  'minified': string;
  'minifiedFullscreenBtnWrapper': string;
  'toggleWorkbench': string;
  'trainerBarVisible': string;
}
declare var cssExports: CssExports;
export = cssExports;
