// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bar': string;
  'baseLegend': string;
  'distanceLegend': string;
  'locationBar': string;
  'section': string;
  'section-long': string;
  'section-short': string;
  'sectionLong': string;
  'sectionShort': string;
}
declare var cssExports: CssExports;
export = cssExports;
