// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bar': string;
  'baseLegend': string;
  'charcoalGrey': string;
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'distanceLegend': string;
  'locationBar': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'section': string;
  'section-long': string;
  'section-short': string;
  'sectionLong': string;
  'sectionShort': string;
  'textDarker': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
