// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'augmentedVirtualityTool': string;
  'blinker': string;
  'btn': string;
  'btn-blink': string;
  'btn-primary': string;
  'btn-primary--hover': string;
  'btnBlink': string;
  'btnPrimary': string;
  'btnPrimaryHover': string;
  'toolButton': string;
  'with-time-series-controls': string;
  'withTimeSeriesControls': string;
}
declare var cssExports: CssExports;
export = cssExports;
