// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'compass': string;
  'innerRing': string;
  'outerRing': string;
  'rotationMarker': string;
}
declare var cssExports: CssExports;
export = cssExports;
