// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'charcoalGrey': string;
  'colorPrimary': string;
  'compass': string;
  'dark': string;
  'darkWithOverlay': string;
  'innerRing': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'outerRing': string;
  'rotationMarker': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
