// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'colorPrimary': string;
  'colorSplitter': string;
  'compass': string;
  'dark': string;
  'darkWithOverlay': string;
  'innerRing': string;
  'outerRing': string;
  'rotationMarker': string;
  'textDarker': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
