// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blinker': string;
  'btn': string;
  'btn-blink': string;
  'btn-primary': string;
  'btn-primary--hover': string;
  'btnBlink': string;
  'btnPrimary': string;
  'btnPrimaryHover': string;
  'charcoalGrey': string;
  'colorPrimary': string;
  'dark': string;
  'darkWithOverlay': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'textLight': string;
  'toolButton': string;
}
declare var cssExports: CssExports;
export = cssExports;
