// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'decrease': string;
  'increase': string;
  'list': string;
  'refresh': string;
  'zoomControl': string;
}
declare var cssExports: CssExports;
export = cssExports;
