// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'charcoalGrey': string;
  'colorPrimary': string;
  'dark': string;
  'darkWithOverlay': string;
  'decrease': string;
  'increase': string;
  'list': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'refresh': string;
  'textDarker': string;
  'textLight': string;
  'zoomControl': string;
}
declare var cssExports: CssExports;
export = cssExports;
