// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'decrease': string;
  'increase': string;
  'list': string;
  'refresh': string;
  'textDarker': string;
  'textLight': string;
  'zoomControl': string;
}
declare var cssExports: CssExports;
export = cssExports;
