// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'charcoalGrey': string;
  'colorPrimary': string;
  'dark': string;
  'darkWithOverlay': string;
  'header': string;
  'label-badge': string;
  'labelBadge': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'small-badge': string;
  'smallBadge': string;
}
declare var cssExports: CssExports;
export = cssExports;
