// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'charcoalGrey': string;
  'clipboard': string;
  'clipboardBody': string;
  'colorPrimary': string;
  'copyBtn': string;
  'dark': string;
  'darkWithOverlay': string;
  'explanation': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'title': string;
  'tooltip': string;
  'tooltip-text': string;
  'tooltip-wrapper': string;
  'tooltip-wrapper--light': string;
  'tooltipText': string;
  'tooltipWrapper': string;
  'tooltipWrapperLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
