// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  clipboard: string;
  clipboardBody: string;
  copyBtn: string;
  explanation: string;
  title: string;
  tooltip: string;
  "tooltip-text": string;
  "tooltip-wrapper": string;
  "tooltip-wrapper--light": string;
  tooltipText: string;
  tooltipWrapper: string;
  tooltipWrapperLight: string;
}
declare var cssExports: CssExports;
export = cssExports;
