// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loader': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'spin': string;
}
declare var cssExports: CssExports;
export = cssExports;
