// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottomOverlay': string;
  'clearOverlay': string;
  'isActive': string;
  'leftOverlay': string;
  'rightOverlay': string;
  'topOverlay': string;
}
declare var cssExports: CssExports;
export = cssExports;
