// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'message-item': string;
  'messageItem': string;
  'sections': string;
}
declare var cssExports: CssExports;
export = cssExports;
