// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  VideoGuideWrapper: string;
  "VideoGuideWrapper--closing": string;
  actions: string;
  captureBtn: string;
  footer: string;
  header: string;
  intro: string;
  isActive: string;
  isHidden: string;
  isVisible: string;
  previewBtn: string;
  "remove-button": string;
  removeBtn: string;
  removeButton: string;
  stories: string;
  story: string;
  "story-fade-in": string;
  "story-fade-out": string;
  "story-panel": string;
  "story-slide-down": string;
  "story-slide-up": string;
  storyFadeIn: string;
  storyFadeOut: string;
  storyPanel: string;
  storySlideDown: string;
  storySlideUp: string;
  trashBtn: string;
  tutBtn: string;
  videoGuide: string;
  "videoGuide--iframe": string;
  videoGuideIframe: string;
  videoGuideLoading: string;
  videoGuideRatio: string;
  videoGuideWrapper: string;
  videoGuideWrapperClosing: string;
}
declare var cssExports: CssExports;
export = cssExports;
