// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'cancelBtn': string;
  'charcoalGrey': string;
  'colorPrimary': string;
  'dark': string;
  'darkWithOverlay': string;
  'doneBtn': string;
  'editor': string;
  'editorHeader': string;
  'field': string;
  'fieldBtn': string;
  'header': string;
  'inner': string;
  'is-mounted': string;
  'isMounted': string;
  'mapButtonColor': string;
  'modalHighlight': string;
  'popupEditor': string;
  'saveBtn': string;
  'textDarker': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
