// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'draggable': string;
  'footer': string;
  'isSuccessful': string;
  'menu': string;
  'menuBtn': string;
  'menuInner': string;
  'recapture': string;
  'story': string;
  'storyHeader': string;
  'toggleBtn': string;
  'viewBtn': string;
}
declare var cssExports: CssExports;
export = cssExports;
