// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'colorPrimary': string;
  'colorSplitter': string;
  'dark': string;
  'darkWithOverlay': string;
  'exitBtn': string;
  'full-panel': string;
  'fullPanel': string;
  'is-hidden': string;
  'is-mounted': string;
  'isActive': string;
  'isCentered': string;
  'isHidden': string;
  'isMounted': string;
  'isPushedUp': string;
  'left': string;
  'locationBtn': string;
  'mobileNavBtn': string;
  'navBtn': string;
  'navBtnMobile': string;
  'nextBtn': string;
  'previousBtn': string;
  'right': string;
  'story': string;
  'story-container': string;
  'storyContainer': string;
  'storyHeader': string;
  'textDarker': string;
  'textLight': string;
}
declare var cssExports: CssExports;
export = cssExports;
