name: npm-publish
on:
  push:
    branches:
      - main

concurrency:
  group: npm-publish
  cancel-in-progress: false

jobs:
  publish:
    permissions:
      contents: write # to create and push a tag and updated attributions
      actions: read
      id-token: write
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Detect a version change
        id: detect
        run: |
          LOCAL_VERSION=$(node -p "require('./package.json').version")
          echo "Current version in package.json: $LOCAL_VERSION"

          IS_ALREADY_PUBLISHED=$(npm view terriajs@$LOCAL_VERSION version 2>/dev/null || echo 'false')

          if [ "$IS_ALREADY_PUBLISHED" != "false" ]; then
            echo "terriajs@$LOCAL_VERSION is already published"
            echo "should_publish=false" >> "$GITHUB_OUTPUT"
          else 
            echo "TerriaJS $LOCAL_VERSION is not published yet, proceeding with publish"
            echo "version=$LOCAL_VERSION" >> "$GITHUB_OUTPUT"
            echo "should_publish=true" >> "$GITHUB_OUTPUT"

            if [[ "$LOCAL_VERSION" == *"-"* ]]; then
              NPM_TAG=$(echo "$LOCAL_VERSION" | sed 's/[^-]*-\([^.]*\).*/\1/')
            else
              NPM_TAG="latest"
            fi
            echo "NPM tag to use: $NPM_TAG"
            echo "npm_tag=$NPM_TAG" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Node.js for NPM
        if: steps.detect.outputs.should_publish == 'true'
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          node-version-file: ".nvmrc"

      - name: Install yarn
        if: steps.detect.outputs.should_publish == 'true'
        run: npm install -g yarn@^1.22.22

      - name: Install dependencies
        if: steps.detect.outputs.should_publish == 'true'
        run: yarn install --ignore-engines
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"

      # - name: Update attributions.md
      #   run: |
      #     git config --global user.email "TerriaBot@users.noreply.github.com"
      #     git config --global user.name "Terria Bot via GitHub Actions"
      #     yarn gulp code-attribution
      #     git add doc/acknowledgements/attributions.md
      #     if ! git diff --cached --quiet; then
      #       git commit -m "Update attributions.md for v${{ steps.detect.outputs.version }}"
      #       git push origin HEAD:${{ github.ref_name }}
      #     fi

      - name: Lint and build terriajs
        if: steps.detect.outputs.should_publish == 'true'
        run: npx gulp lint release
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"

      - name: Publish package to NPM
        if: steps.detect.outputs.should_publish == 'true'
        run: npm publish --tag ${{ steps.detect.outputs.npm_tag }}
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
          NODE_AUTH_TOKEN: ""

      - name: Tag and push the new version to GitHub
        if: steps.detect.outputs.should_publish == 'true'
        run: |
          git config user.name "Terria Bot via GitHub Actions"
          git config user.email "TerriaBot@users.noreply.github.com"
          git tag "${{ steps.detect.outputs.version }}"
          git push origin "${{ steps.detect.outputs.version }}"

      # These slack success and failure message actions can be combined but it means there'll be no notification on a failed
      #  action-detect-and-tag-new-version. It also allows for a bit better message customisation
      - name: Send success notification on Slack
        if: steps.detect.outputs.should_publish == 'true'
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,action,ref
          author_name: ${{ github.workflow }}
          mention: here
          if_mention: always
          text: ":white_check_mark: Published v${{ steps.detect.outputs.version }} to https://www.npmjs.com/package/terriajs"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required

      - name: Send failure or cancellation notification on Slack
        if: failure() || cancelled() # Pick up events even if the job fails or is canceled.
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,action,ref
          author_name: ${{ github.workflow }}
          mention: here
          if_mention: always
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
