name: test-attribution-update
on:
  push:
    branches:
      - test-attribution

jobs:
  update-attribution:
    permissions:
      contents: write # to push the updated attributions.md
      actions: read
    name: Update attributions.md
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Detect a version change and tag the new version
        uses: steve9164/action-detect-and-tag-new-version@v1
        id: detect
        with:
          tag-template: "{VERSION}"
          use-annotated-tag: "true"
          tagger-name: Terria Bot via GitHub Actions
          tagger-email: TerriaBot@users.noreply.github.com
          create-tag: false

      - name: Set up Node.js for NPM
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          node-version-file: ".nvmrc"

      - name: Install yarn
        run: npm install -g yarn@^1.22.22

      - name: Install dependencies
        run: yarn install --ignore-engines
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"

      - name: Update attributions.md
        run: |
          git config --global user.email "info@terria.io"
          git config --global user.name "GitHub Actions"
          yarn gulp code-attribution
          git add doc/acknowledgements/attributions.md
          if ! git diff --cached --quiet; then
            git commit -m "Update attributions.md for v${{ steps.detect.outputs.current-version }}"
            git push origin HEAD:${{ github.ref_name }}
          fi
